version: "3.8"

services:
  multimedia-server-1:
    build: .
    network_mode: host
    environment:
      - SERVER_ID=1
      - SERVER_PORT=5058
      - VIDEO_PATH=/videos
      - FFMPEG_PATH=/usr/bin
    volumes:
      - /home/chris/OneDrive/Documents/8o examino/Multimedia/multisrv/src/main/java/com/multisrv/videos:/videos

  multimedia-server-2:
    build: .
    network_mode: host
    environment:
      - SERVER_ID=2
      - SERVER_PORT=5059
      - VIDEO_PATH=/videos
      - FFMPEG_PATH=/usr/bin
    volumes:
      - /home/chris/OneDrive/Documents/8o examino/Multimedia/multisrv/src/main/java/com/multisrv/videos:/videos

  load-balancer:
    image: nginx:alpine
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - multimedia-server-1
      - multimedia-server-2